aklt/plantuml-syntax

syntax/plantuml.vim

PlantUML supports abstract classes, written as `abstract class { ... }` or just `abstract { ... }`.

Highlight the "abstract" keyword

---

syntax/plantuml.vim

The `setlocal isident+=#` statement makes `isnot#` operator unusable. This code below is the procedure for reproducing.
```vim
vim -u NONE
:echo {} isnot# {}
1
:setlocal isident+=#
:echo {} isnot# {}
E121: Undefined variable: isnot#
E15: Invalid expression: isnot# {}
```
So I cannot use `plantuml-syntax` with other plugins using `isnot#` (such as [vim-rails][]). Maybe this is a vim bug? or methods of vim? I don't know.
[vim-rails]: https://github.com/tpope/vim-rails/blob/master/autoload/rails.vim#L4494
I'm not good for PlantUML, but please remove this statement if not making any problems.

`isnot#` operator cannot be used

---

ftdetect/plantuml.vim

The current filetype detection is just a little wonky. This can be noticed if you comment out either line in the ftdetect/plantuml.vim file, open up a file that should be detected by the remaining line, and checking the makeprg value for the correct script without making any edits. This commit fixed the issue on my system. I'm pretty new to vim scripting, so there may be a better way to accomplish the same task.

Corrected filetype detection

---

ftplugin/plantuml.vim

I have 2 commits:
1. Fix the way the ftplugin is loaded. This way the file is sourced once for each plantuml buffer. It's simpler and more standard.
2. I have added support for the endwise plugin --> https://github.com/tpope/vim-endwise.
This plugin magically completes certain things for you. For example:
```
note left  <<< if you type this and hit enter
end note <<< this will be magically inserted and the cursor placed between the 2 lines
```
However, I see the current syntax file doesn't match some of the plantuml keywords e.g. `loop`. So endwise wont work for them.
I notice that @hokorobi has fixed this in his fork. @hokorobi - any plans for a pull request?

Support endwise

---

syntax/plantuml.vim

By a definition of plantumlClass, partition <partition name> {} it wasn't colored, so it was changed to avoided it.
But class <class name>  {} everything is colored, so it may not be the best definition.
There is no definitions, so plantumlClassArrows deleted.

Support for partition {}

---

indent/plantuml.vim

The pattern I noticed was added.
I use \%(\).
From help
> 	Just like \(\), but without counting it as a sub-expression.  This
>	allows using more groups and it's a little bit faster.

Add indent pattern

---

syntax/plantuml.vim

Since "rectangle" did not exist, it was added.

Add rectangle to plantumlTypeKeyword

---

ftdetect/plantuml.vim
ftplugin/plantuml.vim
syntax/plantuml.vim

"Last Change: " can not keep up with the update, so do not erase it?
I think that it is better to delete "Version:" as well.
How about transferring " syntax/plantuml.vim  TODO:" to Github Issues?

Remove inaccurate Last Change

---

syntax/plantuml.vim

Since {} is also used other than class diagram, I have made plantumlClass available only for class diagram.
before:
after:

plantumlClass available only for class diagrams

---

ftplugin/plantuml.vim
indent/plantuml.vim
syntax/plantuml.vim

Fixed the following warnings presented by [vint](https://github.com/Kuniwak/vint).
- Prefer single quoted strings (see Google VimScript Style Guide (Strings))
- Use scriptencoding when multibyte char exists (see :help :scriptencoding)
- Make the scope explicit like `v:version` (or possibly be unexpected builtin?) (see :help local-variable)

Fix vint warning

---

syntax/plantuml.vim

Example:
```
@startuml
Alice -> Bob: message 1
Bob --> Alice: ok
|||
Alice -> Bob: message 2
Bob --> Alice: ok
||45||
Alice -> Bob: message 3
Bob --> Alice: ok
@enduml
```

Add Space in Sequence Diagram

---

syntax/plantuml.vim

Fix this wrong highlight:
```
@startuml
Alice->Bob : hello
note left: this is a first note
Bob->Alice : ok
note right: this is another note
Bob->Bob : I am thinking
note left
a note
can also be defined
on several lines
end note
@enduml
```

Fix activity label syntax

---

syntax/plantuml.vim

Highlight of the following pattern does not work well, but I PR so I think that it is better than the current.
```
@startuml
skinparam backgroundcolor AntiqueWhite/Gold
skinparam classBackgroundColor Wheat|CornflowerBlue
class Foo #red-green
note left of Foo #blue\9932CC
this is my
note on this class
end note
package example #GreenYellow/LightGoldenRodYellow {
class Dummy
}
@enduml
```

Add multiple lines note syntax

---

ftplugin/plantuml.vim

Currently, plantuml-syntax interpolates the current filename directly into the `makeprg` setting. If the filename changes (_e.g.,_ via `:sav new_filename.uml`), the `makeprg` no longer matches the new file.
Using a literal `%` symbol instead prevents this problem.

Use built-in % filename substitution in makeprg

---

syntax/plantuml.vim

`split ... end` block is a syntax of SDL diagram.
e.g.
```
split
:nak(i)<
:ack(o)>
split again
:ack(i)<
:next(o)
on several lines|
:i := i + 1]
:ack(o)>
split again
:err(i)<
:nak(o)>
split again
:foo/
split again
:i > 5}
stop
end split
```
I added `split` as keyword to highlight it.
ref: http://en.plantuml.com/activity-diagram-beta

Add 'split' for SDL diagram

---

ftdetect/plantuml.vim

For first line, `did_filetype()` should be referred only when the filetype is detected from its file content. For second line, `setfiletype plantuml` is duplicate since `set filetype=plantuml` sets filetype.

Fix 'plantuml' filetype detection

---

indent/plantuml.vim

`fork` and `split` construct blocks and they should increase an indent level. This PR make `fork` and `split` increase indentation.

increase indent level on 'fork' and 'split' blocks

---

README.md
ftplugin/plantuml.vim

This adds a flag `g:plantuml_set_makeprg` to prevent makeprg from being set instead of #65.
I can change the description I wrote in the README if you have any other style you like.

Add flag to prevent makeprg from being set

---

syntax/plantuml.vim

Implement arrow notation.
plantuml-syntax-test/reference_3-26-1.uml

Implement arrow notation

---

syntax/plantuml.vim

Added definitions to highlight <back> etc.
plantuml-syntax-test/reference_1-13-1.uml

Add HTML tag syntax

---

syntax/plantuml.vim

Color names are not case sensitive, so I did the same with syntax.

Ignore case color keywords

---

syntax/plantuml.vim

PlantUML can generate gantt charts.
This PR defines the required keywords.
There is still a problem with : inside a resource definition and with ' when connecting tasks.
In both cases the remaining text on the line will be displayed as a comment.

Add keywords for gantt charts

---

syntax/plantuml.vim

- Update the syntax file from the "java -jar plantuml.jar -language" results.
- "in at are to the and" is moved to plantumlKeyword under "gant".
The keywords added in 3f79146 and 4767a23.

Update syntax based on PlantUML 1.2020.5

---

ftdetect/plantuml.vim

There is no `augroup` command in an `ftdetect` file (see `:help ftdetect`). This breaks plugins loaded after the plantuml-syntax plugin. As an example, if the plantuml-syntax plugin is loaded before the [fatih/vim-go](https://github.com/fatih/vim-go) plugin, the filetype detection for [go.mod](https://github.com/fatih/vim-go/blob/b995086646f29de25acbe7df2c08cc196c4641d7/ftdetect/gofiletype.vim#L12-L19) files breaks.

Do not use 'augroup' in ftdetect

---

syntax/plantuml.vim

If I add a sequence diagram message that contains ":" character, this cause the syntax highlighting to be broken for the rest of that sequence diagram, eg: `mobile_phone -> mobile_phone: send a message containing ":"`
I've never used the use case diagram but based on https://plantuml.com/use-case-diagram, this seems like a reasonable fix.

Actor syntax highlight conflicts with sequence diagram

---

syntax/plantuml.vim

This patch causes delays to be syntax highlighted correctly
when there're space characters before the first dots.
I.e. the text in between the triple dots in the example below is
now highlighted as a delay.
```plantuml
group My own label
Bob -> Alice: Authentication Request
... wait a while ...
Bob <- Alice: Authentication Accepted
end
```

Allow leading space on delay lines

---

syntax/plantuml.vim

This patch causes `end note` in the following example to no longer
be highlighted as text but as keywords.
```plantuml
note right
Some note text.
end note
```

Highlight "end note" as keywords

---

ftdetect/plantuml.vim
ftplugin/plantuml.vim
indent/plantuml.vim
syntax/plantuml.vim

No longer needed due to the removal of the maintainer notation.

Remove scriptencoding

---

syntax/plantuml.vim

Added the `together` type which is basicly an "invisible" `rectangle` used to group graphical component together.
Changed `Labels with a colon` to get the correct spacing allowed by PlantUML. I choose to colorize only the label, not the colon because it's more like an operator. Not part of the label itself.

Small improv
