syntax/plantuml.vim
* boundary
* control
* entity
* database
=> Add missing keywords

ftplugin/plantuml.vim
Add basic comment support and suitable format options.
=> Add comment support

ftplugin/plantuml.vim
Support for [matchit](https://github.com/vim-scripts/matchit.zip).
=> Support for matchit

ftplugin/plantuml.vim
Namely: `alt`, `group` and `legend`.
=> add matchit support for some seq diagram syntax

indent/plantuml.vim
So far this only handles seq diagrams and state diagrams (as these are
what I have been using).
Should easily be extendable to other diagram types by adding to the
s:incIndent and s:decIndent vars.
=> add first stab at indent file

indent/plantuml.vim
This should be merged after #23 as it fixes the issue I raised in my comment there.
=> Update note indent support

syntax/plantuml.vim
=> Add Divider in Sequence Diagram

syntax/plantuml.vim
example1
before:
after:
example2
before:
after:
=> Improve labels with a colon

syntax/plantuml.vim
There was an extra \ before d.
=> Fix "down" in the arrow is not recognized

syntax/plantuml.vim
=> Improve Class Diagram

syntax/plantuml.vim
I thought that it would be better to unify the color of the arrows, but how do you feel?
=> Uniform coloring of arrows

syntax/plantuml.vim
=> Add Stereotypes

syntax/plantuml.vim
Example:
```
@startuml
:Ready;
:next(o)|
:Receiving;
split
:nak(i)<
:ack(o)>
split again
:ack(i)<
:next(o)
on several line|
:i := i + 1]
:ack(o)>
split again
:err(i)<
:nak(o)>
split again
:foo/
split again
:i > 5}
stop
end split
:finish;
@enduml
```
=> Add activity label syntax

syntax/plantuml.vim
Since PlantUML version upgrade added keywords, I followed it.
=> Update keywords from Version 1.2017.15

ftdetect/plantuml.vim, syntax/plantuml.vim
1) add *.puml as plantuml filetype ;
2) replace plain unicode word with \0xc0-\0xff ;
=> 1) add *.puml ; 2) fix unicode problem ;

indent/plantuml.vim
@aklt This pull request resolves indentation problems for all plantumlTypeKeyword types (not just package, but everything you define in the syntax file).
```txt
before:
plantumlTypeKeyword hello {
plantumlTypeKeyword a {
ohno!
}
}
after:
plantumlTypeKeyword hello {
plantumlTypeKeyword a {
yolo!
}
}
```
This PR has been tested on the latest version of neovim; not sure if works on Vim, but I'd be happy if someone were able to check. Assuming it works to your liking, we can use this idea to keep indentation in sync for all parts of the syntax file.
Resolves #55 and supercedes another pull request (https://github.com/aklt/plantuml-syntax/pull/59) that attempts to make a one-off fix.
=> Source code indents properly for all typeKeywords

syntax/plantuml.vim
I tried to improve the matching of arrows. Include #42, #43.
~~There are still some buggy things, so I will try to adjust a bit more.~~
~~https://github.com/aklt/plantuml-syntax-test/blob/master/reference_2-06-1.uml etc.~~
=> Improve matching of arrows

ftdetect/plantuml.vim, ftplugin/plantuml.vim, indent/plantuml.vim, syntax/plantuml.vim
=> Explicitly describe license of source code

README.md, ftdetect/plantuml.vim
See section **Including files or URL** of http://plantuml.com/preprocessing
```
@startuml
!include List.iuml
List <|.. ArrayList
@enduml
```
=> Includes the iuml file extension

indent/plantuml.vim
feat: package can indent.
Document here: http://plantuml.com/class-diagram , search the keyword package.
=> feat: package can indent

indent/plantuml.vim
According to 
https://plantuml.com/fr/ie-diagram
There is a new keyword "intent" that has to be added to the list of keywords for increment indent.
=> Adding "entity" keyword in the increment indent

indent/plantuml.vim
Add words for curly braces block.
=> Update IncIndent target of curly braces block

syntax/plantuml.vim
=> Improve string recognition

indent/plantuml.vim
I simply tried to avoid more indentation.
Please confirm.
fix #92
=> Fix fork again increase indent

syntax/plantuml.vim
=> Update syntax keyword

syntax/plantuml.vim
see https://plantuml.com/fr/style-evolution
Most of the keywords usable in <style> section are identical to those from skinparam.
Some are new.
=> Add some keywords used in <style>..</style> section
